"""Canonical memory layer."""

from .backends import (
    ChromaMemoryVectorStore,
    MongoMemoryDocumentStore,
    Neo4jMemoryGraphStore,
    NoopMemoryGraphStore,
    get_memory_document_store,
    get_memory_graph_store,
    get_memory_vector_store,
)
from .defaults import (
    build_memory_record,
    build_core_memory_records,
    build_experiment_memory_records,
    default_memory_projection,
    default_memory_record_to_artifact,
    dedupe_memory_records,
    ensure_memory_record_defaults,
    fingerprint_for_spec,
    memory_object_spec,
    memory_object_specs,
    record_from_vector_hit,
)
from .fingerprints import fingerprint_json
from .models import (
    CanonicalizationResult,
    MemoryBlobRef,
    MemoryEntity,
    MemoryLineage,
    MemoryObjectSpec,
    MemoryProjection,
    MemoryQuery,
    MemoryRecord,
    MemoryRelation,
    MemoryReuseResult,
    MemorySearchHit,
    MemoryValidity,
    ResearchKGNode,
    ResearchKGRelation,
    ResearchKGUpdate,
)
from .research_kg import build_research_kg_update, canonicalize_concept, knowledge_graph_config
from .service import MemoryService

__all__ = [
    "ChromaMemoryVectorStore",
    "CanonicalizationResult",
    "MemoryBlobRef",
    "MemoryEntity",
    "MemoryLineage",
    "MemoryObjectSpec",
    "MemoryProjection",
    "MemoryQuery",
    "MemoryRecord",
    "MemoryRelation",
    "MemoryReuseResult",
    "MemorySearchHit",
    "MemoryService",
    "MemoryValidity",
    "MongoMemoryDocumentStore",
    "Neo4jMemoryGraphStore",
    "NoopMemoryGraphStore",
    "build_memory_record",
    "build_research_kg_update",
    "build_core_memory_records",
    "build_experiment_memory_records",
    "canonicalize_concept",
    "dedupe_memory_records",
    "default_memory_projection",
    "default_memory_record_to_artifact",
    "ensure_memory_record_defaults",
    "fingerprint_json",
    "fingerprint_for_spec",
    "get_memory_document_store",
    "get_memory_graph_store",
    "get_memory_vector_store",
    "memory_object_spec",
    "memory_object_specs",
    "ResearchKGNode",
    "ResearchKGRelation",
    "ResearchKGUpdate",
    "knowledge_graph_config",
    "record_from_vector_hit",
]
